### ISSUE TITLE
Support translation

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/pretty-cron#1]
Basically, `prettify` should work with other languages.

**Comment by jbondia** [comment]
Hi Addam, I guess I could help with French, German, Italian and Spanish. Could we discuss on how to achieve this?

**Comment by adamchainz** [comment]
Sure. I don't know too much about i18n I'm afraid, but I do know Django does it quite well.

My aim here would be to make this opt-in as well - perhaps we'd have a second function called `prettify_i18n` (or something easier) that can take a language code or use some language environment (e.g. django's, or any other package that supports it?). Then `prettify` can be redirected internally to just `prettify_i18n` with english as the language

**Comment by jbondia** [comment]
I see. What do you think about the 1st option you wrote about, which would be passing a language code? Being English by default. Something like:
`def prettify_i18n(expression, lan='en'):
    # Code here`

Having somewhere (in a file) the constants regarding the sentences in the different languages? There are not many strings to translate.

Just an idea

Cheers

**Comment by adamchainz** [comment]
Well actually we can tack it on to the existing function with a kwarg default like that - `prettify(expression, lang='en')`.

Whether we use `en` or `en-US` to support more finer grained internationalization is another thing.

Also I think the code internally will need adapting to be two-pass. It could change the cron expression into an internal abstract object-passed representation, e.g. `HumanList([days.Monday, days.Thursday])` that then a translator class can provide translations for. Things like lists ("a, b, and c") vary widely between languages.

**Comment by adamchainz** [comment]
Retired in #97 - the recommended replacement, [cron_descriptor](https://pypi.org/project/cron_descriptor/), supports translation.
