### ISSUE TITLE
Support full line parsing

### ISSUE THREAD

**Issue by qlixed** [adamchainz/pretty-cron#65]
Support  the cron full line of parsing
Currently if we do this:
pretty_cron,pretty_cron("0 * * * * /path/to/some/script")
The output will be:
0 * * * * /path/to/some/script
But the idea is to parse the full line is to get an output like this:
"At 0 minutes past every hour of every day will execute: /path/to/some/script"
or some other variant like:
"/path/to/some/script: At 0 minutes past every hour of every day"
If the idea pitch in, I can try to make a PR with the required code.

**Comment by adamchainz** [comment]
Sounds valid, but I think it would probably be best to provide a second function, named e.g. `prettify_crontab_line`. It could then strip off the command and parse the cron, then tack back on "execute: {command}"

**Comment by adamchainz** [comment]
Retired in #97 - the recommended replacement, [cron_descriptor](https://pypi.org/project/cron_descriptor/) could probably be made to support this if it doesn't already.
