### ISSUE TITLE
Alternative to this project

### ISSUE THREAD

**Issue by Salamek** [adamchainz/pretty-cron#7]
Hi, i was using your project for a while, but results was not "satisfying"... here is better alternative i just ported:
https://github.com/Salamek/cron-descriptor
Just letting you know, maybe it will save some of your coding time :smiley_cat:

**Comment by adamchainz** [comment]
Thanks! We coded this in house @YPlan and it's satisfactory for our use cases, that's why it's not fully featured yet.

That port could do with making a bit more pythonic, `descripter.GetDescription(DescriptionTypeEnum.FULL)` stinks a lot of .NET to me!

**Comment by Salamek** [comment]
Well PR's and suggestions are welcomed  :-)
I added some default/key arguments to some methods + PEP8 check...
And i'm thinking about Upper-CamelCase ->  Lower-CamelCase conversion or to snake_case, not decided yet...

**Comment by Salamek** [comment]
@adamchainz ok refactored to pass pep8-naming from version 1.2.0
