### ISSUE TITLE
Does not work for all type of cron expression

### ISSUE THREAD

**Issue by smrrrazu** [adamchainz/pretty-cron#72]
0 */6 * * *
*/5 6-19 30,31,1,2,3,4,14,15,16,17 * *
0 */8 * * *

pretty-cron could not convert the above expression.

**Comment by adamchainz** [comment]
Indeed. Pull requests are welcome...

**Comment by elgalu** [comment]
FYI this is supported by https://github.com/Salamek/cron-descriptor

**Comment by adamchainz** [comment]
I think using cron-descriptor is a good solution
