### ISSUE TITLE
Retire in favour of cron_descriptor

### ISSUE THREAD

**Issue by adamchainz** [adamchainz/pretty-cron#97]
[cron_descriptor](https://pypi.org/project/cron_descriptor/) is much more fully featured and it doesn't make sense to have two different libraries trying to achieve the same thing. `pretty-cron` will be retired in favour of it.

We should publish a new version with 'inactive' PyPI status and messaging around using `cron_descriptor` instead.

**Comment by adamchainz** [comment]
[Version 1.2.0](https://pypi.org/project/pretty-cron/1.2.0/) has been released to retire the library.

**Comment by adamchainz** [comment]
Ok all issues and PR's closed, done here.

Will archive the repo in 3 months time.

**Comment by graingert** [comment]
F
